name: rapidpro-prod
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - sitestatic:/var/www/sitestatic:ro
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      rapidpro: { condition: service_started }
      courier: { condition: service_started }
      mailroom: { condition: service_started }

  # NOTE: postgres and minio services are REMOVED

  elastic:
    image: elasticsearch:7.17.20
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - logger.level=INFO
    # You might want to bind ports in production, or keep it internal
    # ports:
    #  - 9200:9200

  redis:
    image: redis:6.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis:/data
    # You might want to bind ports in production, or keep it internal
    # ports:
    #  - 6379:6379

  rapidpro:
    build:
      context: ./rapidpro/
      args:
        - RAPIDPRO_TAG=v9.2.5
    command: ["webapp"]
    depends_on: # Removed postgres and minio
      elastic: { condition: service_started }
      redis: { condition: service_started }
    environment:
      - MAILROOM_URL=${MAILROOM_URL}
      - DJANGO_SETTINGS_MODULE=temba.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REMOTE_CONTAINERS=true
      - REDIS_URL=${REDIS_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - FCM_API_KEY=${FCM_API_KEY}
      - STORAGE_URL=${STORAGE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_USE_SSL=${AWS_S3_USE_SSL}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-ingo.tuganire.info}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS:-}
      - DJANGO_SECURE_PROXY_SSL_HEADER=${DJANGO_SECURE_PROXY_SSL_HEADER}
      - RAPIDPRO_IP_ADDRESSES=${RAPIDPRO_IP_ADDRESSES}
      - DJANGO_SEND_EMAILS=${DJANGO_SEND_EMAILS}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT}
      - DJANGO_EMAIL_USE_TLS=${DJANGO_EMAIL_USE_TLS}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL}
      - RAPIDPRO_BRAND_DOMAIN=${RAPIDPRO_BRAND_DOMAIN}
      - RAPIDPRO_BRAND_NAME=${RAPIDPRO_BRAND_NAME}
      - RAPIDPRO_BRAND_EMAIL=${RAPIDPRO_BRAND_EMAIL}
      - RAPIDPRO_BRAND_SUPPORT_EMAIL=${RAPIDPRO_BRAND_SUPPORT_EMAIL}
      - RAPIDPRO_BRAND_ALLOW_SIGNUPS=${RAPIDPRO_BRAND_ALLOW_SIGNUPS}
    volumes:
      - sitestatic:/rapidpro/sitestatic

  celery:
    build:
      context: ./rapidpro/
      args:
        - RAPIDPRO_TAG=v9.2.5
    command: ["celery"]
    depends_on:
      rapidpro: { condition: service_started }
    environment:
      - MAILROOM_URL=${MAILROOM_URL}
      - DJANGO_SETTINGS_MODULE=temba.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REMOTE_CONTAINERS=true
      - REDIS_URL=${REDIS_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - FCM_API_KEY=${FCM_API_KEY}
      - STORAGE_URL=${STORAGE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_USE_SSL=${AWS_S3_USE_SSL}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-ingo.tuganire.info}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS:-}
      - DJANGO_SECURE_PROXY_SSL_HEADER=${DJANGO_SECURE_PROXY_SSL_HEADER}
      - RAPIDPRO_IP_ADDRESSES=${RAPIDPRO_IP_ADDRESSES}
      - DJANGO_SEND_EMAILS=${DJANGO_SEND_EMAILS}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT}
      - DJANGO_EMAIL_USE_TLS=${DJANGO_EMAIL_USE_TLS}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL}
      - RAPIDPRO_BRAND_DOMAIN=${RAPIDPRO_BRAND_DOMAIN}
      - RAPIDPRO_BRAND_NAME=${RAPIDPRO_BRAND_NAME}
      - RAPIDPRO_BRAND_EMAIL=${RAPIDPRO_BRAND_EMAIL}
      - RAPIDPRO_BRAND_SUPPORT_EMAIL=${RAPIDPRO_BRAND_SUPPORT_EMAIL}
      - RAPIDPRO_BRAND_ALLOW_SIGNUPS=${RAPIDPRO_BRAND_ALLOW_SIGNUPS}

  mailroom:
    build:
      context: https://github.com/nyaruka/mailroom.git#v9.2.2
      dockerfile: Dockerfile
    depends_on:
      rapidpro: { condition: service_started }
    environment:
      - MAILROOM_ADDRESS=0.0.0.0
      - MAILROOM_DB=${DATABASE_URL_PSG}
      - MAILROOM_ANDROID_CREDENTIALS_FILE=/usr/src/app/firebase-service-account.json
      - MAILROOM_SMTP_SERVER=${MAILROOM_SMTP_SERVER}
      - MAILROOM_REDIS=${REDIS_URL}
      - MAILROOM_ELASTIC=${ELASTICSEARCH_URL}
      - MAILROOM_DOMAIN=${MAILROOM_DOMAIN:-host.docker.internal}
      - MAILROOM_ATTACHMENT_DOMAIN=${MAILROOM_ATTACHMENT_DOMAIN:-host.docker.internal}
      - MAILROOM_DISALLOWED_NETWORKS=${MAILROOM_DISALLOWED_NETWORKS:-}
      - MAILROOM_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - MAILROOM_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MAILROOM_S3_ENDPOINT=${AWS_S3_ENDPOINT_URL}
      - MAILROOM_S3_SESSIONS_BUCKET=${MAILROOM_S3_SESSIONS_BUCKET}
      - MAILROOM_S3_ATTACHMENTS_BUCKET=${MAILROOM_S3_ATTACHMENTS_BUCKET}
      - MAILROOM_S3_LOGS_BUCKET=${MAILROOM_S3_LOGS_BUCKET}
      - MAILROOM_S3_FORCE_PATH_STYLE=false
      - MAILROOM_LOG_LEVEL=info
    volumes:
      - ./firebase-service-account.json:/usr/src/app/firebase-service-account.json:ro

  courier:
    build:
      context: https://github.com/nyaruka/courier.git#v9.2.1
      dockerfile: Dockerfile
    depends_on:
      rapidpro: { condition: service_started }
    environment:
      - COURIER_ADDRESS=0.0.0.0
      - COURIER_DB=${DATABASE_URL_PSG}
      - COURIER_REDIS=${REDIS_URL}
      - COURIER_DOMAIN=${COURIER_DOMAIN:-host.docker.internal}
      - COURIER_BASE_URL=${COURIER_BASE_URL:-https://host.docker.internal}
      - COURIER_DISALLOWED_NETWORKS=${COURIER_DISALLOWED_NETWORKS:-}
      - COURIER_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - COURIER_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COURIER_S3_ENDPOINT=${AWS_S3_ENDPOINT_URL}
      - COURIER_S3_ATTACHMENTS_BUCKET=${COURIER_S3_ATTACHMENTS_BUCKET}
      - COURIER_S3_LOGS_BUCKET=${COURIER_S3_LOGS_BUCKET}
      - COURIER_S3_FORCE_PATH_STYLE=false
      - COURIER_LOG_LEVEL=info

  indexer:
    build:
      context: https://github.com/nyaruka/rp-indexer.git#v9.2.0
      dockerfile: Dockerfile
    depends_on:
      rapidpro: { condition: service_started }
    environment:
      - INDEXER_DB=${DATABASE_URL_PSG}
      - INDEXER_ELASTIC_URL=${ELASTICSEARCH_URL}
      - INDEXER_LOG_LEVEL=info

volumes:
  # NOTE: postgres and minio volumes are REMOVED
  elastic:
  redis:
  sitestatic:
